### ISSUE TITLE
Flashing firmware and bootloader

### ISSUE THREAD

**Issue by letshin** [konstantinwerner/numpad#2]
I can't seem to get the bootloader to flash and to get DFU working. I've flashed this with avrdude but can't get a USB device detected:

avrdude.exe -p atmega32u4 -c stk500v1 -b 19200 -U flash:w:"ATMega32U4-usbdevice_dfu-1_0_0.hex":i -P COM7 -U lfuse:w:0xFE:m	-U hfuse:w:0x99:m	-U efuse:w:0xFF:m

any advice please?

**Comment by stdlogicvector** [comment]
I didn't have notifications turned on, so I missed your question. It seems like you got it working, what was the problem?

**Comment by letshin** [comment]
A couple of things, hardware-wise the v supply was swapped around by the fab factory, then the datasheet for the sheet said that the bootloader wasn't flashed but that's actually an error as they come pre-flashed.

Other errors were because the USB wasn't soldered properly but I finally figured out how to solder it after some tries - messed up a couple of boards but got there in the end.
